// Choice Properties — Replit Static File Server
// Serves the static site and injects config.js from environment variables.
// Optimisations:
//   • Nav + footer injected server-side → eliminates 2 fetch() calls per page
//   • First-page property data pre-fetched and embedded in listings.html
//     as window.__INITIAL_LISTINGS__ → properties paint immediately on load
//   • Strong Cache-Control headers on static assets (CSS/JS/fonts/images)
//   • config.js served no-cache so env-var changes show instantly

const http = require('http');
const https = require('https');
const fs   = require('fs');
const path = require('path');
const PORT = parseInt(process.env.PORT || '5000', 10);
const ROOT = __dirname;

// ── Config from env vars ───────────────────────────────────────────────────
const config = {
  SUPABASE_URL:      process.env.SUPABASE_URL      || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
  SITE_URL:          (process.env.SITE_URL || '').replace(/\/$/, ''),
  APPLY_FORM_URL:    (process.env.APPLY_FORM_URL || '').replace(/\/$/, ''),
  IMAGEKIT_URL:      process.env.IMAGEKIT_URL        || '',
  IMAGEKIT_PUBLIC_KEY: process.env.IMAGEKIT_PUBLIC_KEY || '',
  GEOAPIFY_API_KEY:  process.env.GEOAPIFY_API_KEY   || '',
  COMPANY_NAME:      process.env.COMPANY_NAME        || 'Choice Properties',
  COMPANY_EMAIL:     process.env.COMPANY_EMAIL       || 'hello@choiceproperties.com',
  COMPANY_PHONE:     process.env.COMPANY_PHONE       || '',
  COMPANY_TAGLINE:   process.env.COMPANY_TAGLINE     || 'Your trust is our standard.',
  COMPANY_ADDRESS:   process.env.COMPANY_ADDRESS     || '',
  LEASE_DEFAULT_LATE_FEE_FLAT:  Number(process.env.LEASE_DEFAULT_LATE_FEE_FLAT)  || 50,
  LEASE_DEFAULT_LATE_FEE_DAILY: Number(process.env.LEASE_DEFAULT_LATE_FEE_DAILY) || 10,
  LEASE_DEFAULT_EXPIRY_DAYS:    Number(process.env.LEASE_DEFAULT_EXPIRY_DAYS)    || 7,
  FEATURES: {
    CO_APPLICANT:     process.env.FEATURE_CO_APPLICANT     !== 'false',
    VEHICLE_INFO:     process.env.FEATURE_VEHICLE_INFO     !== 'false',
    DOCUMENT_UPLOAD:  process.env.FEATURE_DOCUMENT_UPLOAD  !== 'false',
    MESSAGING:        process.env.FEATURE_MESSAGING        !== 'false',
    REALTIME_UPDATES: process.env.FEATURE_REALTIME_UPDATES !== 'false',
  },
};

// ── config.js content ─────────────────────────────────────────────────────
const configJs = `// Auto-generated by server.js — do not edit directly
const CONFIG = ${JSON.stringify(config, null, 2)};

// Image helper used by property cards
CONFIG.img = function(url, tr) {
  if (!url || !CONFIG.IMAGEKIT_URL) return url || '';
  const base = CONFIG.IMAGEKIT_URL.replace(/\\/$/, '');
  const transforms = {
    card:       'tr:w-600,q-80,f-webp',
    card_2x:    'tr:w-1200,q-80,f-webp',
    gallery:    'tr:w-1200,q-90,f-webp',
    gallery_2x: 'tr:w-2400,q-85,f-webp',
    strip:      'tr:w-80,h-60,c-maintain_ratio,q-70,f-webp',
    thumb:      'tr:w-120,h-120,c-maintain_ratio,q-75,f-webp',
    lightbox:   'tr:q-95,f-webp',
    og:         'tr:w-1200,h-630,c-force,fo-center,q-85,f-webp',
    avatar:     'tr:w-80,h-80,c-force,fo-face,q-80,f-webp',
    avatar_lg:  'tr:w-160,h-160,c-force,fo-face,q-85,f-webp',
  };
  const t = transforms[tr] || transforms.gallery;
  if (url.startsWith(CONFIG.IMAGEKIT_URL)) {
    const clean = url.replace(/\\/tr:[^/]+/, '');
    return clean.replace(CONFIG.IMAGEKIT_URL, CONFIG.IMAGEKIT_URL + '/' + t);
  }
  return url;
};

CONFIG.srcset = function(url, tr1, tr2) {
  const u1 = CONFIG.img(url, tr1);
  const u2 = CONFIG.img(url, tr2);
  if (!u1) return '';
  if (!u2 || u2 === u1) return u1;
  return u1 + ' 1x, ' + u2 + ' 2x';
};

Object.freeze(CONFIG);
Object.freeze(CONFIG.FEATURES);
`;

// ── Nav + footer: read once at startup ────────────────────────────────────
let navHtml    = '';
let footerHtml = '';
try {
  navHtml    = fs.readFileSync(path.join(ROOT, 'components/nav.html'),    'utf8');
  footerHtml = fs.readFileSync(path.join(ROOT, 'components/footer.html'), 'utf8');
  console.log('✓ Nav + footer components loaded');
} catch (e) {
  console.warn('⚠ Could not read nav/footer components:', e.message);
}

// ── Property cache (server-side pre-fetch for listings.html) ──────────────
const PROPERTY_CACHE_TTL = 3 * 60 * 1000; // 3 minutes
let propertyCache     = null;
let propertyCacheTime = 0;

function fetchListingsFromSupabase() {
  const supabaseUrl = config.SUPABASE_URL;
  const anonKey     = config.SUPABASE_ANON_KEY;
  if (!supabaseUrl || !anonKey) return Promise.resolve(null);

  const PER_PAGE = 24;
  const apiPath  =
    '/rest/v1/properties' +
    '?select=*,landlords(contact_name,business_name,avatar_url,verified)' +
    '&status=eq.active' +
    '&order=created_at.desc' +
    `&limit=${PER_PAGE}` +
    '&offset=0';

  const urlObj  = new URL(supabaseUrl + apiPath);
  const options = {
    hostname: urlObj.hostname,
    path:     urlObj.pathname + urlObj.search,
    method:   'GET',
    headers: {
      'apikey':        anonKey,
      'Authorization': `Bearer ${anonKey}`,
      'Prefer':        'count=exact',
    },
    timeout: 8000,
  };

  return new Promise((resolve) => {
    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', (chunk) => { body += chunk; });
      res.on('end', () => {
        // Supabase returns 206 Partial Content when Prefer: count=exact is used
        if (res.statusCode !== 200 && res.statusCode !== 206) {
          console.warn(`⚠ Property cache: Supabase returned HTTP ${res.statusCode} — ${body.slice(0, 200)}`);
          resolve(null); return;
        }
        try {
          const rows = JSON.parse(body);
          if (!Array.isArray(rows)) { console.warn('⚠ Property cache: unexpected response shape'); resolve(null); return; }
          let total = rows.length;
          const rangeHeader = res.headers['content-range'];
          if (rangeHeader) {
            const m = rangeHeader.match(/\/(\d+)/);
            if (m) total = parseInt(m[1], 10);
          }
          resolve({
            rows,
            total,
            page:        1,
            per_page:    PER_PAGE,
            total_pages: Math.ceil(total / PER_PAGE),
          });
        } catch (e) {
          console.warn('⚠ Property cache: parse error —', e.message);
          resolve(null);
        }
      });
    });
    req.on('error', (e) => { console.warn('⚠ Property cache: network error —', e.message); resolve(null); });
    req.on('timeout', () => { req.destroy(); console.warn('⚠ Property cache: timed out'); });
    req.end();
  });
}

async function refreshPropertyCache() {
  const data = await fetchListingsFromSupabase();
  if (data) {
    propertyCache     = data;
    propertyCacheTime = Date.now();
    console.log(`✓ Property cache refreshed — ${data.rows.length} listings (total: ${data.total})`);
  } else {
    console.warn('⚠ Property cache fetch failed — serving without pre-loaded data');
  }
}

// Warm the cache at startup, then refresh every 3 minutes
refreshPropertyCache();
setInterval(refreshPropertyCache, PROPERTY_CACHE_TTL);

// ── HTML injection helper ─────────────────────────────────────────────────
// Injects nav+footer into every HTML response.
// Optionally embeds initial property data for listings.html.
function injectIntoHtml(html, filePath) {
  // Inject nav
  if (navHtml) {
    html = html.replace(/<div\s+id="site-nav"\s*><\/div>/g,
      `<div id="site-nav" data-server-injected="1">${navHtml}</div>`);
  }
  // Inject footer
  if (footerHtml) {
    html = html.replace(/<div\s+id="site-footer"\s*><\/div>/g,
      `<div id="site-footer" data-server-injected="1">${footerHtml}</div>`);
  }
  // Embed initial property data for listings.html only
  const isListings = filePath.endsWith('listings.html');
  if (isListings && propertyCache) {
    // Strip any build-time snapshot baked in by generate-config.js so we don't double-inject
    html = html.replace(/<script[^>]*>window\.__INITIAL_LISTINGS__[\s\S]*?<\/script>\n?/g, '');
    const dataScript =
      `<script>window.__INITIAL_LISTINGS__=${JSON.stringify(propertyCache)};` +
      `window.__INITIAL_LISTINGS_TS__=${propertyCacheTime};</script>`;
    html = html.replace('</head>', dataScript + '\n</head>');
  }
  return html;
}

// ── MIME types ────────────────────────────────────────────────────────────
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.js':   'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg':  'image/svg+xml',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.ico':  'image/x-icon',
  '.woff': 'font/woff',
  '.woff2':'font/woff2',
  '.ttf':  'font/ttf',
  '.txt':  'text/plain; charset=utf-8',
  '.xml':  'application/xml; charset=utf-8',
  '.webmanifest': 'application/manifest+json',
  '.zip':  'application/zip',
};

// Cache-Control headers per asset type
// HTML: no-cache (always revalidate so injected data is fresh)
// Static assets: immutable for 1 year (content-hashed via ?v= params)
function cacheHeader(ext) {
  if (ext === '.html')               return 'no-cache';
  if (['.css','.js'].includes(ext))  return 'public, max-age=31536000, immutable';
  if (['.woff','.woff2','.ttf','.svg','.png','.jpg','.jpeg','.webp','.ico'].includes(ext))
                                     return 'public, max-age=31536000, immutable';
  return 'public, max-age=3600';
}

// ── File server ───────────────────────────────────────────────────────────
function serveFile(res, filePath, statusCode) {
  const ext  = path.extname(filePath).toLowerCase();
  const mime = MIME[ext] || 'application/octet-stream';
  try {
    if (ext === '.html') {
      let html = fs.readFileSync(filePath, 'utf8');
      html = injectIntoHtml(html, filePath);
      res.writeHead(statusCode || 200, {
        'Content-Type':  mime,
        'Cache-Control': cacheHeader(ext),
      });
      res.end(html);
    } else {
      const data = fs.readFileSync(filePath);
      res.writeHead(statusCode || 200, {
        'Content-Type':  mime,
        'Cache-Control': cacheHeader(ext),
      });
      res.end(data);
    }
  } catch {
    res.writeHead(404, { 'Content-Type': 'text/html' });
    const notFound = path.join(ROOT, '404.html');
    res.end(fs.existsSync(notFound) ? fs.readFileSync(notFound) : '<h1>404 Not Found</h1>');
  }
}

// ── HTTP server ───────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
  let urlPath = req.url.split('?')[0];

  // Serve dynamically generated config.js (always no-cache)
  if (urlPath === '/config.js') {
    res.writeHead(200, {
      'Content-Type':  'application/javascript; charset=utf-8',
      'Cache-Control': 'no-store',
    });
    return res.end(configJs);
  }

  // Redirect browser-auto-requested icons to the SVG favicon
  if (
    urlPath === '/favicon.ico' ||
    urlPath === '/apple-touch-icon.png' ||
    urlPath === '/apple-touch-icon-precomposed.png'
  ) {
    res.writeHead(302, { 'Location': '/assets/favicon.svg' });
    return res.end();
  }

  // Resolve file path
  let filePath = path.join(ROOT, urlPath);

  // Security: prevent path traversal outside ROOT
  if (!filePath.startsWith(ROOT)) {
    res.writeHead(403);
    return res.end('Forbidden');
  }

  // Directory → index.html
  if (fs.existsSync(filePath) && fs.statSync(filePath).isDirectory()) {
    filePath = path.join(filePath, 'index.html');
  }

  // No extension → try .html
  if (!fs.existsSync(filePath) && !path.extname(urlPath)) {
    const withHtml = filePath + '.html';
    if (fs.existsSync(withHtml)) filePath = withHtml;
  }

  if (!fs.existsSync(filePath)) {
    const notFound = path.join(ROOT, '404.html');
    res.writeHead(404, { 'Content-Type': 'text/html; charset=utf-8' });
    return res.end(fs.existsSync(notFound) ? fs.readFileSync(notFound) : '<h1>404 Not Found</h1>');
  }

  serveFile(res, filePath);
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`Choice Properties server running on port ${PORT}`);
  console.log(`SUPABASE_URL:      ${config.SUPABASE_URL      ? '✓ set' : '✗ missing'}`);
  console.log(`SUPABASE_ANON_KEY: ${config.SUPABASE_ANON_KEY ? '✓ set' : '✗ missing'}`);
  console.log(`IMAGEKIT_URL:      ${config.IMAGEKIT_URL      ? '✓ set' : '✗ missing'}`);
  console.log(`GEOAPIFY_API_KEY:  ${config.GEOAPIFY_API_KEY  ? '✓ set' : '✗ missing'}`);
});
