from sqlalchemy import Column, String, Integer, Float, Boolean, Text
from sqlalchemy.sql import func
from database.db import Base


class Property(Base):
    __tablename__ = "properties"

    id = Column(String, primary_key=True)
    source = Column(String, nullable=False)
    source_url = Column(String)
    source_listing_id = Column(String)

    status = Column(String, default="scraped")

    title = Column(String)
    address = Column(String)
    city = Column(String)
    state = Column(String)
    zip = Column(String)
    county = Column(String)
    lat = Column(Float)
    lng = Column(Float)
    bedrooms = Column(Integer)
    bathrooms = Column(Float)
    half_bathrooms = Column(Integer)
    square_footage = Column(Integer)
    lot_size_sqft = Column(Integer)
    monthly_rent = Column(Integer)
    property_type = Column(String)
    year_built = Column(Integer)
    floors = Column(Integer)
    unit_number = Column(String)
    total_units = Column(Integer)
    description = Column(Text)
    showing_instructions = Column(Text)
    available_date = Column(String)
    parking = Column(String)
    garage_spaces = Column(Integer)
    pets_allowed = Column(Boolean)
    pet_types_allowed = Column(Text)
    pet_weight_limit = Column(Integer)
    pet_details = Column(Text)
    smoking_allowed = Column(Boolean)
    lease_terms = Column(Text)
    minimum_lease_months = Column(Integer)
    security_deposit = Column(Integer)
    last_months_rent = Column(Integer)
    application_fee = Column(Integer)
    pet_deposit = Column(Integer)
    admin_fee = Column(Integer)
    move_in_special = Column(Text)
    parking_fee = Column(Integer)
    amenities = Column(Text)
    appliances = Column(Text)
    utilities_included = Column(Text)
    flooring = Column(Text)
    heating_type = Column(String)
    cooling_type = Column(String)
    laundry_type = Column(String)
    total_bathrooms = Column(Float)
    has_basement = Column(Boolean)
    has_central_air = Column(Boolean)
    virtual_tour_url = Column(String)

    original_image_urls = Column(Text)
    local_image_paths = Column(Text, default="[]")

    original_data = Column(Text)
    edited_fields = Column(Text, default="[]")
    data_quality_score = Column(Integer)
    missing_fields = Column(Text, default="[]")
    inferred_features = Column(Text, default="[]")

    published_at = Column(String)
    choice_property_id = Column(String)

    scraped_at = Column(String, default=func.now())
    updated_at = Column(String, default=func.now())
